### ISSUE TITLE
Error loading service BBC

### ISSUE THREAD

**Issue by Akirainblack** [vinefeeder/VineFeeder#1]
I'm having issues using the BBC:
I'm running Windows 11 with python 3.12.7
I've pulled the latest version today, run the pip install -r requirements.txt
I have get_iplayer latest version installed.
and am trying to download Shetland S09E05:
`
[info] Loaded service: BBC

Keyword(s) for search Shetland
Searching for Shetland
╭────────────── info ──────────────╮
│                                  │
│ There are 9 series for Shetland. │
│ You may choose from 1 to 9.      │
│                                  │
╰──────────────────────────────────╯
Series to download? 9

Error loading service: BBC
Try again
`
It does offer the episode list but when I select any I get the Error loading service.
Please can you advise as to what I'm doing wrong?

**Comment by vinefeeder** [comment]
![Screenshot from 2024-12-05 19-29-35](https://github.com/user-attachments/assets/f9126df3-31e6-4180-964a-0b47457f225d)

**Comment by Akirainblack** [comment]
I'm sorry, I had just assumed it used get_iplayer.
All services are giving me the error.

<img width="590" alt="image" src="https://github.com/user-attachments/assets/fba3292c-7b18-43fe-acdc-896e2819f25d">

I've pulled the latest version and run the pip install again.
I am running 24H2 in case that makes any difference.
Is there any way I can get any more information so I can try to work out what's wrong?

**Comment by vinefeeder** [comment]
You DO have Devine installed correctly? And you HAVE read the README  that says Devine needs to be able to download all services from the command line before you install VineFeeder?

I'

**Comment by Akirainblack** [comment]
Yes, I do have Devine installed correctly, I have read the readme through and through but can't see any reference to "download all services" I'm sorry I know I'm the one making the mistakes and this isn't what you want to deal with.

**Comment by vinefeeder** [comment]
"First be sure Devine works correctly to your liking,". Please don't play
semantics.

Clearly if none of your downloads work your downloader is at fault.  I have
no idea how you installed Devine but would hazard a guess you followed
someone on VH rather than following Devine guidance. ( See what I did
there?)

pip install devine

 Your most obvious action would be to try running a direct Devine command
in the VineFeeder folder.  If it doesn't work there install devine
correctly.  If Devine works there then probably there is a package clash
somewhere.

 I installed Devine to Windows 11 as instructed. I installed, via git,
devine-services. Then configured devine for command line use with all
services. I installed VineFeeder via a git clone. I ran pip install -r
requirements.txt and everything ran sweetly.

This is not a VineFeeder error and, I'm sorry, not my responsibility to
help sort out your issue.  Please ask on VH about installing devine so it
runs from anywhere on your system.

 I deliberately moved off VH to avoid conversations like this. Please think
it through yourself and respect my privacy.
